### ISSUE TITLE
NZAOA Demo Milestone

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/ITR#26]
Demonstrate ITR for NZAOA:

- [ ] Data and Benchmark scope
- [ ] Sample Portfolio (as provided/signed off by NZAOA)
- [ ] ITR temperature scoring
- [ ] UI and UX
- [ ] Test Cases/Quality Checks
- [ ] Documentation
